export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_ERROR = 'REGISTER_USER_ERROR';


export const SET_LOADING = 'SET_LOADING';


export const LOGIN_USER = "LOGIN_USER";
export const LOGIN_USER_SUCCESS = "LOGIN_USER_SUCCESS";
export const LOGIN_USER_ERROR = "LOGIN_USER_ERROR";

export const SET_TOKEN_SUCCESS = "SET_TOKEN_SUCCESS";
export const CHECK_FOR_TOKING = "CHECK_FOR_TOKING";
export const SET_TOKEN_ERROR = "SET_TOKEN_ERROR";

export const REFRESH_TOKEN_SUCCESS = "REFRESH_TOKEN_SUCCESS";
export const REFRESH_TOKEN_ERROR = "REFRESH_TOKEN_ERROR";

export const GET_ROUTE_TO_PROTECT = "GET_ROUTE_TO_PROTECT";
export const GET_ROUTE_TO_PROTECT_SUCCESS = "GET_ROUTE_TO_PROTECT_SUCCESS";
export const GET_ROUTE_TO_PROTECT_ERROR = "GET_ROUTE_TO_PROTECT_ERROR";
/*----------------------------------------  BUSINESS --------------------------------------------*/
export const GET_BUSINESS = "GET_BUSINESS";
export const GET_BUSINESS_SUCCESS = "GET_BUSINESS_SUCCESS";
export const GET_BUSINESS_ERROR = "GET_BUSINESS_ERROR";

export const ADD_BUSINESS = "ADD_BUSINESS";
export const ADD_BUSINESS_SUCCESS = "ADD_BUSINESS_SUCCESS";
export const ADD_BUSINESS_ERROR = "ADD_BUSINESS_ERROR";

export const ADD_MULTIPLE_BUSINESS = "ADD_MULTIPLE_BUSINESS";
export const ADD_MULTIPLE_BUSINESS_SUCCESS = "ADD_MULTIPLE_BUSINESS_SUCCESS";
export const ADD_MULTIPLE_BUSINESS_ERROR = "ADD_MULTIPLE_BUSINESS_ERROR";

export const UPDATE_BUSINESS = "UPDATE_BUSINESS";
export const UPDATE_BUSINESS_SUCCESS = "UPDATE_BUSINESS_SUCCESS";
export const UPDATE_BUSINESS_ERROR = "UPDATE_BUSINESS_ERROR";

export const DELETE_BUSINESS = "DELETE_BUSINESS";
export const DELETE_BUSINESS_SUCCESS = "DELETE_BUSINESS_SUCCESS";
export const DELETE_BUSINESS_ERROR = "DELETE_BUSINESS_ERROR";

export const GET_BUSINESS_NATURES = "GET_BUSINESS_NATURES";
export const GET_BUSINESS_NATURES_SUCCESS = "GET_BUSINESS_NATURES_SUCCESS";
export const GET_BUSINESS_NATURES_ERROR = "GET_BUSINESS_NATURES_ERROR";

export const ADD_BUSINESS_NATURES = "ADD_BUSINESS_NATURES";
export const ADD_BUSINESS_NATURES_SUCCESS = "ADD_BUSINESS_NATURES_SUCCESS";
export const ADD_BUSINESS_NATURES_ERROR = "ADD_BUSINESS_NATURES_ERROR";

export const ADD_MULTIPLE_BUSINESS_NATURES = "ADD_MULTIPLE_BUSINESS_NATURES";
export const ADD_MULTIPLE_BUSINESS_NATURES_SUCCESS =
    "ADD_MULTIPLE_BUSINESS_NATURES_SUCCESS";
export const ADD_MULTIPLE_BUSINESS_NATURES_ERROR =
    "ADD_MULTIPLE_BUSINESS_NATURES_ERROR";

export const UPDATE_BUSINESS_NATURES = "UPDATE_BUSINESS_NATURES";
export const UPDATE_BUSINESS_NATURES_SUCCESS =
    "UPDATE_BUSINESS_NATURES_SUCCESS";
export const UPDATE_BUSINESS_NATURES_ERROR = "UPDATE_BUSINESS_NATURES_ERROR";

export const DELETE_BUSINESS_NATURES = "DELETE_BUSINESS_NATURES";
export const DELETE_BUSINESS_NATURES_SUCCESS =
    "DELETE_BUSINESS_NATURES_SUCCESS";
export const DELETE_BUSINESS_NATURES_ERROR = "DELETE_BUSINESS_NATURES_ERROR";

export const GET_BUSINESS_SITUATIONS = "GET_BUSINESS_SITUATIONS";
export const GET_BUSINESS_SITUATIONS_SUCCESS =
    "GET_BUSINESS_SITUATIONS_SUCCESS";
export const GET_BUSINESS_SITUATIONS_ERROR = "GET_BUSINESS_SITUATIONS_ERROR";

export const ADD_BUSINESS_SITUATIONS = "ADD_BUSINESS_SITUATIONS";
export const ADD_BUSINESS_SITUATIONS_SUCCESS =
    "ADD_BUSINESS_SITUATIONS_SUCCESS";
export const ADD_BUSINESS_SITUATIONS_ERROR = "ADD_BUSINESS_SITUATIONS_ERROR";

export const ADD_MULTIPLE_BUSINESS_SITUATIONS =
    "ADD_MULTIPLE_BUSINESS_SITUATIONS";
export const ADD_MULTIPLE_BUSINESS_SITUATIONS_SUCCESS =
    "ADD_MULTIPLE_BUSINESS_SITUATIONS_SUCCESS";
export const ADD_MULTIPLE_BUSINESS_SITUATIONS_ERROR =
    "ADD_MULTIPLE_BUSINESS_SITUATIONS_ERROR";

export const UPDATE_BUSINESS_SITUATIONS = "UPDATE_BUSINESS_SITUATIONS";
export const UPDATE_BUSINESS_SITUATIONS_SUCCESS =
    "UPDATE_BUSINESS_SITUATIONS_SUCCESS";
export const UPDATE_BUSINESS_SITUATIONS_ERROR =
    "UPDATE_BUSINESS_SITUATIONS_ERROR";

export const DELETE_BUSINESS_SITUATIONS = "DELETE_BUSINESS_SITUATIONS";
export const DELETE_BUSINESS_SITUATIONS_SUCCESS =
    "DELETE_BUSINESS_SITUATIONS_SUCCESS";
export const DELETE_BUSINESS_SITUATIONS_ERROR =
    "DELETE_BUSINESS_SITUATIONS_ERROR";
/*---------------------------------------------------------- FolderTech  ----------------------------------------*/

export const GET_FOLDERTECH = "GET_FOLDERTECH";
export const GET_FOLDERTECH_SUCCESS = "GET_FOLDERTECH_SUCCESS";
export const GET_FOLDERTECH_ERROR = "GET_FOLDERTECH_ERROR";

export const ADD_FOLDERTECH = "ADD_FOLDERTECH";
export const ADD_FOLDERTECH_SUCCESS = "ADD_FOLDERTECH_SUCCESS";
export const ADD_FOLDERTECH_ERROR = "ADD_FOLDERTECH_ERROR";


export const UPDATE_FOLDERTECH = "UPDATE_FOLDERTECH";
export const UUPDATE_FOLDERTECH_SUCCESS = "UUPDATE_FOLDERTECH_SUCCESS";
export const UPDATE_FOLDERTECH_ERROR = "UPDATE_FOLDERTECH_ERROR";

export const DELETE_FOLDERTECH = "DELETE_FOLDERTECH";
export const DELETE_FOLDERTECH_SUCCESS = "DELETE_FOLDERTECH_SUCCESS";
export const DELETE_FOLDERTECH_ERROR = "DELETE_FOLDERTECH_ERROR";

export const GET_FOLDERTECH_NATURES = "GET_FOLDERTECH_NATURES";
export const GET_FOLDERTECH_NATURES_SUCCESS = "GET_FOLDERTECH_NATURES_SUCCESS";
export const GET_FOLDERTECH_NATURES_ERROR = "GET_FOLDERTECH_NATURES_ERROR";

export const ADD_FOLDERTECH_NATURES = "ADD_FOLDERTECH_NATURES";
export const ADD_FOLDERTECH_NATURES_SUCCESS = "ADD_FOLDERTECH_NATURES_SUCCESS";
export const ADD_FOLDERTECH_NATURES_ERROR = "ADD_FOLDERTECH_NATURES_ERROR";

export const ADD_MULTIPLE_FOLDERTECH_NATURES =
    "ADD_MULTIPLE_FOLDERTECH_NATURES";
export const ADD_MULTIPLE_FOLDERTECH_NATURES_SUCCESS =
    "ADD_MULTIPLE_FOLDERTECH_NATURES_SUCCESS";
export const ADD_MULTIPLE_FOLDERTECH_NATURES_ERROR =
    "ADD_MULTIPLE_FOLDERTECH_NATURES_ERROR";

export const UPDATE_FOLDERTECH_NATURES = "UPDATE_FOLDERTECH_NATURES";
export const UPDATE_FOLDERTECH_NATURES_SUCCESS =
    "UPDATE_FOLDERTECH_NATURES_SUCCESS";
export const UPDATE_FOLDERTECH_NATURES_ERROR =
    "UPDATE_FOLDERTECH_NATURES_ERROR";

export const DELETE_FOLDERTECH_NATURES = "DELETE_FOLDERTECH_NATURES";
export const DELETE_FOLDERTECH_NATURES_SUCCESS =
    "DELETE_FOLDERTECH_NATURES_SUCCESS";
export const DELETE_FOLDERTECH_NATURES_ERROR =
    "DELETE_FOLDERTECH_NATURES_ERROR";

export const GET_FOLDERTECH_SITUATIONS = "GET_FOLDERTECH_SITUATIONS";
export const GET_FOLDERTECH_SITUATIONS_SUCCESS =
    "GET_FOLDERTECH_SITUATIONS_SUCCESS";
export const GET_FOLDERTECH_SITUATIONS_ERROR =
    "GET_FOLDERTECH_SITUATIONS_ERROR";

export const ADD_FOLDERTECH_SITUATIONS = "ADD_FOLDERTECH_SITUATIONS";
export const ADD_FOLDERTECH_SITUATIONS_SUCCESS =
    "ADD_FOLDERTECH_SITUATIONS_SUCCESS";
export const ADD_FOLDERTECH_SITUATIONS_ERROR =
    "ADD_FOLDERTECH_SITUATIONS_ERROR";

export const ADD_MULTIPLE_FOLDERTECH_SITUATIONS =
    "ADD_MULTIPLE_FOLDERTECH_SITUATIONS";
export const ADD_MULTIPLE_FOLDERTECH_SITUATIONS_SUCCESS =
    "ADD_MULTIPLE_FOLDERTECH_SITUATIONS_SUCCESS";
export const ADD_MULTIPLE_FOLDERTECH_SITUATIONS_ERROR =
    "ADD_MULTIPLE_FOLDERTECH_SITUATIONS_ERROR";

export const UPDATE_FOLDERTECH_SITUATIONS = "UPDATE_FOLDERTECH_SITUATIONS";
export const UPDATE_FOLDERTECH_SITUATIONS_SUCCESS =
    "UPDATE_FOLDERTECH_SITUATIONS_SUCCESS";
export const UPDATE_FOLDERTECH_SITUATIONS_ERROR =
    "UPDATE_FOLDERTECH_SITUATIONS_ERROR";

export const DELETE_FOLDERTECH_SITUATIONS = "DELETE_FOLDERTECH_SITUATIONS";
export const DELETE_FOLDERTECH_SITUATIONS_SUCCESS =
    "DELETE_FOLDERTECH_SITUATIONS_SUCCESS";
export const DELETE_FOLDERTECH_SITUATIONS_ERROR =
    "DELETE_FOLDERTECH_SITUATIONS_ERROR";

/* -------------------------------------------------------- Intermediates --------------------------------*/

export const GET_INTERMEDIATES = "GET_INTERMEDIATES";
export const GET_INTERMEDIATES_SUCCESS = "GET_INTERMEDIATES_SUCCESS";
export const GET_INTERMEDIATE_ERROR = "GET_INTERMEDIATE_ERROR";

export const ADD_INTERMEDIATE = "ADD_INTERMEDIATE";
export const ADD_INTERMEDIATE_SUCCESS = "ADD_INTERMEDIATE_SUCCESS";
export const ADD_INTERMEDIATE_ERROR = "ADD_INTERMEDIATE_ERROR";

export const ADD_MULTIPLE_INTERMEDIATE = "ADD_MULTIPLE_INTERMEDIATE";
export const ADD_MULTIPLE_INTERMEDIATE_SUCCESS =
    "ADD_MULTIPLE_INTERMEDIATE_SUCCESS";
export const ADD_MULTIPLE_INTERMEDIATE_ERROR =
    "ADD_MULTIPLE_INTERMEDIATE_ERROR";

export const UPDATE_INTERMEDIATE = "UPDATE_INTERMEDIATE";
export const UPDATE_INTERMEDIATE_SUCCESS = "UPDATE_INTERMEDIATE_SUCCESS";
export const UPDATE_INTERMEDIATE_ERROR = "UPDATE_INTERMEDIATE_ERROR";

export const DELETE_INTERMEDIATE = "DELETE_INTERMEDIATE";
export const DELETE_INTERMEDIATE_SUCCESS = "DELETE_INTERMEDIATE_SUCCESS";
export const DELETE_INTERMEDIATE_ERROR = "DELETE_INTERMEDIATE_ERROR";

/* -------------------------------------------------------- Clients --------------------------------*/

export const GET_CLIENTS = "GET_CLIENTS";
export const GET_CLIENTS_SUCCESS = "GET_CLIENTS_SUCCESS";
export const GET_CLIENTS_ERROR = "GET_CLIENTS_ERROR";

export const ADD_CLIENT = "ADD_CLIENT";
export const ADD_CLIENT_SUCCESS = "ADD_CLIENT_SUCCESS";
export const ADD_CLIENT_ERROR = "ADD_CLIENT_ERROR";

export const ADD_MULTIPLE_CLIENT = "ADD_MULTIPLE_CLIENT";
export const ADD_MULTIPLE_CLIENT_SUCCESS = "ADD_MULTIPLE_CLIENT_SUCCESS";
export const ADD_MULTIPLE_CLIENT_ERROR = "ADD_MULTIPLE_CLIENT_ERROR";

export const GET_CLIENT_FOR_SELECT = "GET_CLIENT_FOR_SELECT";
export const GET_CLIENT_FOR_SELECT_SUCCESS = "GET_CLIENT_FOR_SELECT_SUCCESS";
export const GET_CLIENT_FOR_SELECT_ERROR = "GET_CLIENT_FOR_SELECT_ERROR";

export const UPDATE_CLIENT = "UPDATE_CLIENT";
export const UPDATE_CLIENT_SUCCESS = "UPDATE_CLIENT_SUCCESS";
export const UPDATE_CLIENT_ERROR = "UPDATE_CLIENT_ERROR";

export const DELETE_CLIENT = "DELETE_CLIENT";
export const DELETE_CLIENT_SUCCESS = "DELETE_CLIENT_SUCCESS";
export const DELETE_CLIENT_ERROR = "DELETE_CLIENT_ERROR";
/* -------------------------------------------------------- Employee --------------------------------*/

export const GET_EMPLOYEES = "GET_EMPLOYEES";
export const GET_EMPLOYEES_SUCCESS = "GET_EMPLOYEES_SUCCESS";
export const GET_EMPLOYEES_ERROR = "GET_EMPLOYEES_ERROR";

export const ADD_EMPLOYEE = "ADD_EMPLOYEE";
export const ADD_EMPLOYEE_SUCCESS = "ADD_EMPLOYEE_SUCCESS";
export const ADD_EMPLOYEE_ERROR = "ADD_EMPLOYEE_ERROR";


export const UPDATE_EMPLOYEE = "UPDATE_EMPLOYEE";
export const UPDATE_EMPLOYEE_SUCCESS = "UPDATE_EMPLOYEE_SUCCESS";
export const UPDATE_EMPLOYEE_ERROR = "UPDATE_EMPLOYEE_ERROR";

export const DELETE_EMPLOYEE = "DELETE_EMPLOYEE";
export const DELETE_EMPLOYEE_SUCCESS = "DELETE_EMPLOYEE_SUCCESS";
export const DELETE_EMPLOYEE_ERROR = "DELETE_EMPLOYEE_ERROR";

export const DOWNLOAD_EMPLOYEE_DOCUMENTS = "DOWNLOAD_EMPLOYEE_DOCUMENTS";
export const DOWNLOAD_EMPLOYEE_DOCUMENTS_SUCCESS = "DOWNLOAD_EMPLOYEE_DOCUMENTS_SUCCESS";
export const DOWNLOAD_EMPLOYEE_DOCUMENTS_ERROR = "DOWNLOAD_EMPLOYEE_DOCUMENTS_ERROR";
/*-------------------------------------------------------------- AutoComplete --------------------------------------------*/

export const GET_AUTOCOMPLETE = "GET_AUTOCOMPLETE";
export const GET_AUTOCOMPLETE_SUCCESS = "GET_AUTOCOMPLETE_SUCCESS";
export const GET_AUTOCOMPLETE_ERROR = "GET_AUTOCOMPLETE_ERROR";
export const SET_AUTOCOMPLETE_OPEN_TO_TRUE = "SET_AUTOCOMPLETE_OPEN_TO_TRUE";
export const SET_AUTOCOMPLETE_OPEN_TO_FALSE = "SET_AUTOCOMPLETE_OPEN_TO_FALSE";


/*----------------------------------------------------------------- Messagerie -----------------------------------------------*/


export const GET_CONVERSATIONS = 'GET_CONVERSATIONS';
export const GET_CONVERSATIONS_SUCCESS = 'GET_CONVERSATIONS_SUCCESS';
export const GET_CONVERSATIONS_ERROR = 'GET_CONVERSATIONS_ERROR';


export const GET_MESSAGES = 'GET_MESSAGES';
export const GET_MESSAGES_SUCCESS = 'GET_MESSAGES_SUCCESS';
export const GET_MESSAGES_ERROR = 'GET_MESSAGES_ERROR';

export const GET_CONVERSATION = 'GET_CONVERSATION';
export const GET_CONVERSATION_SUCCESS = 'GET_CONVERSATION_SUCCESS';
export const GET_CONVERSATION_ERROR = 'GET_CONVERSATION_ERROR';

export const GET_USER = 'GET_USER';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_ERROR = 'GET_USER_ERROR';


export const OPENED_CONVERSATION = 'OPENED_CONVERSATION';
export const ADD_MESSAGES = 'ADD_MESSAGES';
export const ADD_MESSAGE = 'ADD_MESSAGE';
export const LOAD_PREVIOUS_MESSAGES = 'LOAD_PREVIOUS_MESSAGES';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const LOAD_MESSAGES = 'LOAD_MESSAGES';
export const MARK_AS_READ = 'MARK_AS_READ';
export const PREPEND_MESSAGES = 'PREPEND_MESSAGES';
export const SET_USER = 'SET_USER';
export const INCREMENT_UNRREAD = 'INCREMENT_UNRREAD';
export const INCREMENT_UNRREAD_TO_DOCUMENT = 'INCREMENT_UNRREAD_TO_DOCUMENT';
export const INCREMENT_UNRREAD_NOTIFICATIONS_TO_DOCUMENT = 'INCREMENT_UNRREAD_NOTIFICATIONS_TO_DOCUMENT';
export const READ_MESSAGE = 'READ_MESSAGE';
export const ADD_CONVERSATIONS = 'ADD_CONVERSATIONS';
export const ADD_SINGLE_CONVERSATIONS = 'ADD_SINGLE_CONVERSATIONS';
export const LOAD_CONVERSATIONS = 'LOAD_CONVERSATIONS';
export const MESSAGE_RECIEVED = 'MESSAGE_RECIEVED';


export const DOWNLOAD_FILE_FROM = "DOWNLOAD_FILE_FROM";
export const DOWNLOAD_FILE_FROM_SUCCESS = "DOWNLOAD_FILE_FROM_SUCCESS";
export const DOWNLOAD_FILE_FROM_ERROR = "DOWNLOAD_FILE_FROM_ERROR";


export const GET_LOCATION = "GET_LOCATION";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_LOCATION_ERROR = "GET_LOCATION_ERROR";


export const GET_ALL_LOCATED_BRIGADES = "GET_ALL_LOCATED_BRIGADES";
export const GET_ALL_LOCATED_BRIGADES_SUCCESS = "GET_ALL_LOCATED_BRIGADES_SUCCESS";
export const GET_ALL_LOCATED_BRIGADES_ERROR = "GET_ALL_LOCATED_BRIGADES_ERROR";


export const GET_LOCATIONS = "GET_LOCATIONS";
export const GET_LOCATIONS_SUCCESS = "GET_LOCATIONS_SUCCESS";
export const GET_LOCATIONS_ERROR = "GET_LOCATIONS_ERROR";
export const SET_POSITION = "SET_POSITION";


export const GET_MISSIONS = 'GET_MISSIONS';
export const GET_MISSIONS_SUCCESS = 'GET_MISSIONS_SUCCESS';
export const GET_MISSIONS_ERROR = 'GET_MISSIONS_ERROR';

export const ADD_MISSIONS = 'ADD_MISSIONS';
export const ADD_MISSIONS_SUCCESS = 'ADD_MISSIONS_SUCCESS';
export const ADD_MISSIONS_ERROR = 'ADD_MISSIONS_ERROR';


export const UPDATE_MISSIONS = 'UPDATE_MISSIONS';
export const UPDATE_MISSIONS_SUCCESS = 'UPDATE_MISSIONS_SUCCESS';
export const UPDATE_MISSIONS_ERROR = 'UPDATE_MISSIONS_ERROR';

export const DELETE_MISSIONS = 'DELETE_MISSIONS';
export const DELETE_MISSIONS_SUCCESS = 'DELETE_MISSIONS_SUCCESS';
export const DELETE_MISSIONS_ERROR = 'DELETE_MISSIONS_ERROR';


export const GET_GREAT_CONSULTATION_SITE = 'GET_GREAT_CONSULTATION_SITE';
export const GET_GREAT_CONSULTATION_SITE_SUCCESS = 'GET_GREAT_CONSULTATION_SITE_SUCCESS';
export const GET_GREAT_CONSULTATION_SITE_ERROR = 'GET_GREAT_CONSULTATION_SITE_ERROR';

export const ADD_GREAT_CONSULTATION_SITE = 'ADD_GREAT_CONSULTATION_SITE';
export const ADD_GREAT_CONSULTATION_SITE_SUCCESS = 'ADD_GREAT_CONSULTATION_SITE_SUCCESS';
export const ADD_GREAT_CONSULTATION_SITE_ERROR = 'ADD_GREAT_CONSULTATION_SITE_ERROR';


export const UPDATE_GREAT_CONSULTATION_SITE = 'UPDATE_GREAT_CONSULTATION_SITE';
export const UPDATE_GREAT_CONSULTATION_SITE_SUCCESS = 'UPDATE_GREAT_CONSULTATION_SITE_SUCCESS';
export const UPDATE_GREAT_CONSULTATION_SITE_ERROR = 'UPDATE_GREAT_CONSULTATION_SITE_ERROR';

export const DETAILS_GREAT_CONSULTATION_SITE = 'DETAILS_GREAT_CONSULTATION_SITE';
export const DETAILS_GREAT_CONSULTATION_SITE_SUCCESS = 'DETAILS_GREAT_CONSULTATION_SITE_SUCCESS';
export const DETAILS_GREAT_CONSULTATION_SITE_ERROR = 'DETAILS_GREAT_CONSULTATION_SITE_ERROR';


export const GET_STATISTIQUES_GREAT_CONSULTATION_SITE = 'GET_STATISTIQUES_GREAT_CONSULTATION_SITE';
export const GET_STATISTIQUES_GREAT_CONSULTATION_SITE_SUCCESS = 'GET_STATISTIQUES_GREAT_CONSULTATION_SITE_SUCCESS';
export const GET_STATISTIQUES_GREAT_CONSULTATION_SITE_ERROR = 'GET_STATISTIQUES_GREAT_CONSULTATION_SITE_ERROR';

export const GET_STATISTIQUES_TO_ADMIN = 'GET_STATISTIQUES_TO_ADMIN';
export const GET_STATISTIQUES_TO_ADMIN_SUCCESS = 'GET_STATISTIQUES_TO_ADMIN_SUCCESS';
export const GET_STATISTIQUES_TO_ADMIN_ERROR = 'GET_STATISTIQUES_TO_ADMIN_ERROR';


export const DELETE_GREAT_CONSULTATION_SITE = 'DELETE_GREAT_CONSULTATION_SITE';
export const DELETE_GREAT_CONSULTATION_SITE_SUCCESS = 'DELETE_GREAT_CONSULTATION_SITE_SUCCESS';
export const DELETE_GREAT_CONSULTATION_SITE_ERROR = 'DELETE_GREAT_CONSULTATION_SITE_ERROR';


export const GET_GREAT_CADASTRAL_CONSULTATION = 'GET_GREAT_CADASTRAL_CONSULTATION';
export const GET_GREAT_CADASTRAL_CONSULTATION_SUCCESS = 'GET_GREAT_CADASTRAL_CONSULTATION_SUCCESS';
export const GET_GREAT_CADASTRAL_CONSULTATION_ERROR = 'GET_GREAT_CADASTRAL_CONSULTATION_ERROR';

export const ADD_MULTIPLE_CADASTRAL_CONSULTATION = 'ADD_MULTIPLE_CADASTRAL_CONSULTATION';
export const ADD_MULTIPLE_CADASTRAL_CONSULTATION_SUCCESS = 'ADD_MULTIPLE_CADASTRAL_CONSULTATION_SUCCESS';
export const ADD_MULTIPLE_CADASTRAL_CONSULTATION_ERROR = 'ADD_MULTIPLE_CADASTRAL_CONSULTATION_ERROR';

export const Add_Date = 'Add_Date';


export const GET_USER_WITH_PERMISSION = 'GET_USER_WITH_PERMISSION';
export const GET_USER_WITH_PERMISSION_SUCCESS = 'GET_USER_WITH_PERMISSION_SUCCESS';
export const GET_USER_WITH_PERMISSION_ERROR = 'GET_USER_WITH_PERMISSION_ERROR';

export const HANDL_MULTI_CHANGE = 'HANDL_MULTI_CHANGE';

export const SET_USER_WITH_PERMISSION = 'SET_USER_WITH_PERMISSION';
export const SET_USER_WITH_PERMISSION_SUCCESS = 'SET_USER_WITH_PERMISSION_SUCCESS';
export const SET_USER_WITH_PERMISSION_ERROR = 'SET_USER_WITH_PERMISSION_ERROR';


export const GET_LOAD = 'GET_LOAD';
export const GET_LOAD_SUCCESS = 'GET_LOAD_SUCCESS';
export const GET_LOAD_ERROR = 'GET_LOAD_ERROR';


export const GET_STATISTIQUES_LOAD = 'GET_STATISTIQUES_LOAD';
export const GET_STATISTIQUES_LOAD_SUCCESS = 'GET_STATISTIQUES_LOAD_SUCCESS';
export const GET_STATISTIQUES_LOAD_ERROR = 'GET_STATISTIQUES_LOAD_ERROR';

export const ADD_LOAD = 'ADD_LOAD';
export const ADD_LOAD_SUCCESS = 'ADD_LOAD_SUCCESS';
export const ADD_LOAD_ERROR = 'ADD_LOAD_ERROR';


export const UPDATE_LOAD = 'UPDATE_LOAD';
export const UPDATE_LOAD_SUCCESS = 'UPDATE_LOAD_SUCCESS';
export const UPDATE_LOAD_ERROR = 'UPDATE_LOAD_ERROR';


export const DELETE_LOAD = 'DELETE_LOAD';
export const DELETE_LOAD_SUCCESS = 'DELETE_LOAD_SUCCESS';
export const DELETE_LOAD_ERROR = 'DELETE_LOAD_ERROR';


export const GET_CHARGES = 'GET_CHARGES';
export const GET_CHARGES_SUCCESS = 'GET_CHARGES_SUCCESS';
export const GET_CHARGES_ERROR = 'GET_CHARGES_ERROR';

export const GET_INVOICE_STATUS_TO_SELECT = 'GET_INVOICE_STATUS_TO_SELECT';
export const GET_INVOICE_STATUS_TO_SELECT_SUCCESS = 'GET_INVOICE_STATUS_TO_SELECT_SUCCESS';
export const GET_INVOICE_STATUS_TO_SELECT_ERROR = 'GET_INVOICE_STATUS_TO_SELECT_ERROR';

export const ADD_CHARGES = 'ADD_CHARGES';
export const ADD_CHARGES_SUCCESS = 'ADD_CHARGES_SUCCESS';
export const ADD_CHARGES_ERROR = 'ADD_CHARGES_ERROR';


export const UPDATE_CHARGES = 'UPDATE_CHARGES';
export const UPDATE_CHARGES_SUCCESS = 'UPDATE_CHARGES_SUCCESS';
export const UPDATE_CHARGES_ERROR = 'UPDATE_CHARGES_ERROR';


export const DELETE_CHARGES = 'DELETE_CHARGES';
export const DELETE_CHARGES_SUCCESS = 'DELETE_CHARGES_SUCCESS';
export const DELETE_CHARGES_ERROR = 'DELETE_CHARGES_ERROR';


export const GET_LOAD_TYPES = 'GET_LOAD_TYPES';
export const GET_LOAD_TYPES_SUCCESS = 'GET_LOAD_TYPES_SUCCESS';
export const GET_LOAD_TYPES_ERROR = 'GET_LOAD_TYPES_ERROR';


export const GET_LOAD_RELATED_TO = 'GET_LOAD_RELATED_TO';
export const GET_LOAD_RELATED_TO_SUCCESS = 'GET_LOAD_RELATED_TO_SUCCESS';
export const GET_LOAD_RELATED_TO_ERROR = 'GET_LOAD_RELATED_TO_ERROR';


export const GET_CLIENT_BY_ID = 'GET_CLIENT_BY_ID';
export const GET_CLIENT_BY_ID_SUCCESS = 'GET_CLIENT_BY_ID_SUCCESS';
export const GET_CLIENT_BY_ID_ERROR = 'GET_CLIENT_BY_ID_ERROR';

export const GET_BUSINESS_SITUATION_BY_ID = 'GET_BUSINESS_SITUATION_BY_ID';
export const GET_BUSINESS_SITUATION_BY_ID_SUCCESS = 'GET_BUSINESS_SITUATION_BY_ID_SUCCESS';
export const GET_BUSINESS_SITUATION_BY_ID_ERROR = 'GET_BUSINESS_SITUATION_BY_ID_ERROR';


export const GET_FOLDER_TECH_SITUATION_BY_ID = 'GET_FOLDER_TECH_SITUATION_BY_ID';
export const GET_FOLDER_TECH_SITUATION_BY_ID_SUCCESS = 'GET_FOLDER_TECH_SITUATION_BY_ID_SUCCESS';
export const GET_FOLDER_TECH_SITUATION_BY_ID_ERROR = 'GET_FOLDER_TECH_SITUATION_BY_ID_ERROR';


export const GET_FOLDER_TECH_NATURE_BY_NAME = 'GET_FOLDER_TECH_NATURE_BY_NAME';
export const GET_FOLDER_TECH_NATURE_BY_NAME_SUCCESS = 'GET_FOLDER_TECH_NATURE_BY_NAME_SUCCESS';
export const GET_FOLDER_TECH_NATURE_BY_NAME_ERROR = 'GET_FOLDER_TECH_NATURE_BY_NAME_ERROR';


export const GET_BUSINESS_NATURE_BY_NAME = 'GET_BUSINESS_NATURE_BY_NAME';
export const GET_BUSINESS_NATURE_BY_NAME_SUCCESS = 'GET_BUSINESS_NATURE_BY_NAME_SUCCESS';
export const GET_BUSINESS_NATURE_BY_NAME_ERROR = 'GET_BUSINESS_NATURE_BY_NAME_ERROR';


export const GET_INTERMEDIATES_BY_ID = 'GET_INTERMEDIATES_BY_ID';
export const GET_INTERMEDIATES_BY_ID_SUCCESS = 'GET_INTERMEDIATES_BY_ID_SUCCESS';
export const GET_INTERMEDIATES_BY_ID_ERROR = 'GET_INTERMEDIATES_BY_ID_ERROR';


export const GET_LOAD_NATURES = 'GET_LOAD_NATURES';
export const GET_LOAD_NATURES_SUCCESS = 'GET_LOAD_NATURES_SUCCESS';
export const GET_LOAD_NATURES_ERROR = 'GET_LOAD_NATURES_ERROR';

export const ADD_LOAD_NATURES = 'ADD_LOAD_NATURES';
export const ADD_LOAD_NATURES_SUCCESS = 'ADD_LOAD_NATURES_SUCCESS';
export const ADD_LOAD_NATURES_ERROR = 'ADD_LOAD_NATURES_ERROR';

export const ADD_MULTIPLE_LOAD_NATURES = 'ADD_MULTIPLE_LOAD_NATURES';
export const ADD_MULTIPLE_LOAD_NATURES_SUCCESS = 'ADD_MULTIPLE_LOAD_NATURES_SUCCESS';
export const ADD_MULTIPLE_LOAD_NATURES_ERROR = 'ADD_MULTIPLE_LOAD_NATURES_ERROR';


export const UPDATE_LOAD_NATURES = 'UPDATE_LOAD_NATURES';
export const UPDATE_LOAD_NATURES_SUCCESS = 'UPDATE_LOAD_NATURES_SUCCESS';
export const UPDATE_LOAD_NATURES_ERROR = 'UPDATE_LOAD_NATURES_ERROR';

export const DELETE_LOAD_NATURES = 'DELETE_LOAD_NATURES';
export const DELETE_LOAD_NATURES_SUCCESS = 'DELETE_LOAD_NATURES_SUCCESS';
export const DELETE_LOAD_NATURES_ERROR = 'DELETE_LOAD_NATURES_ERROR';

export const GET_CHARGES_NATURES = 'GET_CHARGES_NATURES';
export const GET_CHARGES_NATURES_SUCCESS = 'GET_CHARGES_NATURES_SUCCESS';
export const GET_CHARGES_NATURES_ERROR = 'GET_CHARGES_NATURES_ERROR';


export const GET_CHARGES_NATURES_TO_SELECT = 'GET_CHARGES_NATURES_TO_SELECT';
export const GET_CHARGES_NATURES_TO_SELECT_SUCCESS = 'GET_CHARGES_NATURES_TO_SELECT_SUCCESS';
export const GET_CHARGES_NATURES_TO_SELECT_ERROR = 'GET_CHARGES_NATURES_TO_SELECT_ERROR';

export const ADD_CHARGES_NATURES = 'ADD_CHARGES_NATURES';
export const ADD_CHARGES_NATURES_SUCCESS = 'ADD_CHARGES_NATURES_SUCCESS';
export const ADD_CHARGES_NATURES_ERROR = 'ADD_CHARGES_NATURES_ERROR';


export const UPDATE_CHARGES_NATURES = 'UPDATE_CHARGES_NATURES';
export const UPDATE_CHARGES_NATURES_SUCCESS = 'UPDATE_CHARGES_NATURES_SUCCESS';
export const UPDATE_CHARGES_NATURES_ERROR = 'UPDATE_CHARGES_NATURES_ERROR';

export const DELETE_CHARGES_NATURES = 'DELETE_CHARGES_NATURES';
export const DELETE_CHARGES_NATURES_SUCCESS = 'DELETE_CHARGES_NATURES_SUCCESS';
export const DELETE_CHARGES_NATURES_ERROR = 'DELETE_CHARGES_NATURES_ERROR';

export const GET_INVOICE_STATUS = 'GET_INVOICE_STATUS';
export const GET_INVOICE_STATUS_SUCCESS = 'GET_INVOICE_STATUS_SUCCESS';
export const GET_INVOICE_STATUS_ERROR = 'GET_INVOICE_STATUS_ERROR';

export const ADD_INVOICE_STATUS = 'ADD_INVOICE_STATUS';
export const ADD_INVOICE_STATUS_SUCCESS = 'ADD_INVOICE_STATUS_SUCCESS';
export const ADD_INVOICE_STATUS_ERROR = 'ADD_INVOICE_STATUS_ERROR';


export const UPDATE_INVOICE_STATUS = 'UPDATE_INVOICE_STATUS';
export const UPDATE_INVOICE_STATUS_SUCCESS = 'UPDATE_INVOICE_STATUS_SUCCESS';
export const UPDATE_INVOICE_STATUS_ERROR = 'UPDATE_INVOICE_STATUS_ERROR';

export const DELETE_INVOICE_STATUS = 'DELETE_INVOICE_STATUS';
export const DELETE_INVOICE_STATUS_SUCCESS = 'DELETE_INVOICE_STATUS_SUCCESS';
export const DELETE_INVOICE_STATUS_ERROR = 'DELETE_INVOICE_STATUS_ERROR';


export const GET_FOLDER_TECH_BY_ID = 'GET_FOLDER_TECH_BY_ID';
export const GET_FOLDER_TECH_BY_ID_SUCCESS = 'GET_FOLDER_TECH_BY_ID_SUCCESS';
export const GET_FOLDER_TECH_BY_ID_ERROR = 'GET_FOLDER_TECH_BY_ID_ERROR';

export const GET_BUSINESS_BY_ID = 'GET_BUSINESS_BY_ID';
export const GET_BUSINESS_BY_ID_SUCCESS = 'GET_BUSINESS_BY_ID_SUCCESS';
export const GET_BUSINESS_BY_ID_ERROR = 'GET_BUSINESS_BY_ID_ERROR';


export const GET_BUSINESS_FEES = 'GET_BUSINESS_FEES';
export const GET_BUSINESS_FEES_SUCCESS = 'GET_BUSINESS_FEES_SUCCESS';
export const GET_BUSINESS_FEES_ERROR = 'GET_BUSINESS_FEES_ERROR';


export const GET_FOLDER_TECH_FEES = 'GET_FOLDER_TECH_FEES';
export const GET_FOLDER_TECH_FEES_SUCCESS = 'GET_FOLDER_TECH_FEES_SUCCESS';
export const GET_FOLDER_TECH_FEES_ERROR = 'GET_FOLDER_TECH_FEES_ERROR';


export const ADD_FOLDER_TECH_FEES = 'ADD_FOLDER_TECH_FEES';
export const ADD_FOLDER_TECH_FEES_SUCCESS = 'ADD_FOLDER_TECH_FEES_SUCCESS';
export const ADD_FOLDER_TECH_FEES_ERROR = 'ADD_FOLDER_TECH_FEES_ERROR';


export const ADD_BUSINESS_FEES = 'ADD_BUSINESS_FEES';
export const ADD_BUSINESS_FEES_SUCCESS = 'ADD_BUSINESS_FEES_SUCCESS';
export const ADD_BUSINESS_FEES_ERROR = 'ADD_BUSINESS_FEES_ERROR';

export const PRINT_BILL = 'PRINT_BILL';
export const PRINT_BILL_SUCCESS = 'PRINT_BILL_SUCCESS';
export const PRINT_BILL_ERROR = 'PRINT_BILL_ERROR';

export const CLIENT_BILL_SELECT = 'CLIENT_BILL_SELECT';
export const CLIENT_BILL_SELECT_SUCCESS = 'CLIENT_BILL_SELECT_SUCCESS';
export const CLIENT_BILL_SELECT_ERROR = 'CLIENT_BILL_SELECT_ERROR';


export const UPDATE_FOLDER_TECH_FEES = 'UPDATE_FOLDER_TECH_FEES';
export const UPDATE_FOLDER_TECH_FEES_SUCCESS = 'UPDATE_FOLDER_TECH_FEES_SUCCESS';
export const UPDATE_FOLDER_TECH_FEES_ERROR = 'UPDATE_FOLDER_TECH_FEES_ERROR';


export const UPDATE_BUSINESS_FEES = 'UPDATE_BUSINESS_FEES';
export const UPDATE_BUSINESS_FEES_SUCCESS = 'UPDATE_BUSINESS_FEES_SUCCESS';
export const UPDATE_BUSINESS_FEES_ERROR = 'UPDATE_BUSINESS_FEES_ERROR';

export const DOWNLOAD_FILE_TO_FILE_MANAGER = "DOWNLOAD_FILE_TO_FILE_MANAGER";
export const DOWNLOAD_FILE_TO_FILE_MANAGER_SUCCESS = "DOWNLOAD_FILE_TO_FILE_MANAGER_SUCCESS";
export const DOWNLOAD_FILE_TO_FILE_MANAGER_ERROR = "DOWNLOAD_FILE_TO_FILE_MANAGER_ERROR";


export const GET_SEARCH_RESULTS_DETAILS = 'GET_SEARCH_RESULTS_DETAILS';
export const GET_SEARCH_RESULTS = 'GET_SEARCH_RESULTS';
export const SET_SEARCH_RESULTS_DETAILS = 'SET_SEARCH_RESULTS_DETAILS';
export const SET_SEARCH_RESULTS = 'SET_SEARCH_RESULTS';
export const SET_SEARCH_ERROR = 'SET_SEARCH_ERROR';
//
// export const GET_FOLDERTECH_SITUATION_AUTOCOMPLETE = 'GET_FOLDERTECH_SITUATION_AUTOCOMPLETE';
// export const GET_FOLDERTECH_SITUATION_AUTOCOMPLETE_SUCCESS = 'GET_FOLDERTECH_SITUATION_AUTOCOMPLETE_SUCCESS';
// export const GET_FOLDERTECH_SITUATION_AUTOCOMPLETE_ERROR = 'GET_FOLDERTECH_SITUATION_AUTOCOMPLETE_ERROR';
//
//
// export const GET_INTERMEDIATE_AUTOCOMPLETE = 'GET_INTERMEDIATE_AUTOCOMPLETE';
// export const GET_INTERMEDIATE_AUTOCOMPLETE_SUCCESS = 'GET_INTERMEDIATE_AUTOCOMPLETE_SUCCESS';
// export const GET_INTERMEDIATE_AUTOCOMPLETE_ERROR = 'GET_INTERMEDIATE_AUTOCOMPLETE_ERROR';
//
// export const GET_CLIENT_AUTOCOMPLETE = 'GET_CLIENT_AUTOCOMPLETE';
// export const GET_CLIENT_AUTOCOMPLETE_SUCCESS = 'GET_CLIENT_AUTOCOMPLETE_SUCCESS';
// export const GET_CLIENT_AUTOCOMPLETE_ERROR = 'GET_CLIENT_AUTOCOMPLETE_ERROR';
//
// export const GET_RESP_AUTOCOMPLETE = 'GET_RESP_AUTOCOMPLETE';
// export const GET_RESP_AUTOCOMPLETE_SUCCESS = 'GET_RESP_AUTOCOMPLETE_SUCCESS';
// export const GET_RESP_AUTOCOMPLETE_ERROR = 'GET_RESP_AUTOCOMPLETE_ERROR';
//
// export const GET_FOLDERTECH_NAME_AUTOCOMPLETE = 'GET_FOLDERTECH_NAME_AUTOCOMPLETE';
// export const GET_FOLDERTECH_NAME_AUTOCOMPLETE_SUCCESS = 'GET_FOLDERTECH_NAME_AUTOCOMPLETE_SUCCESS';
// export const GET_FOLDERTECH_NAME_AUTOCOMPLETE_ERROR = 'GET_FOLDERTECH_NAME_AUTOCOMPLETE_ERROR';
//
//
// export const GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE = 'GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE';
// export const GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE_SUCCESS = 'GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE_SUCCESS';
// export const GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE_ERROR = 'GET_NATURES_BUSINESS_NAME_AUTOCOMPLETE_ERROR';

export const OPEN_UPDATE_MODAL = "OPEN_UPDATE_MODAL";
export const OPEN_UPDATE_MODAL_SUCCESS = "OPEN_UPDATE_MODAL_SUCCESS";
//
// export const GET_USER_WITH_PERMISSION = "GET_USER_WITH_PERMISSION";
// export const GET_USER_WITH_PERMISSION_SUCCESS =
//   "GET_USER_WITH_PERMISSION_SUCCESS";
// export const GET_USER_WITH_PERMISSION_ERROR = "GET_USER_WITH_PERMISSION_ERROR";
//
// export const Add_Date = "Add_Date";


export const GET_LOG = 'GET_LOG';
export const SET_LOG_ERROR = 'SET_LOG_ERROR';
export const SET_LOG = 'SET_LOG';
export const SET_LOG_LOADING = 'SET_LOG_LOADING';


export const GET_STATISTICS = 'GET_STATISTICS';
export const SET_STATISTICS_ERROR = 'SET_STATISTICS_ERROR';
export const SET_STATISTICS = 'SET_STATISTICS';
export const SET_STATISTICS_LOADING = 'SET_STATISTICS_LOADING';
export const SET_STATISTICS_SELECTED = 'SET_STATISTICS_SELECTED';
export const SET_STATISTICS_RAPPORT_SELECTED = 'SET_STATISTICS_RAPPORT_SELECTED';


export const GET_NOTIFICATIONS = 'GET_NOTIFICATIONS';
export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS';
export const SET_NOTIFICATIONS_LOADING = 'SET_NOTIFICATIONS_LOADING';

export const LOGS_RECIEVED = 'LOGS_RECIEVED';
export const LOGS_RECIEVED_SUCCESS = 'LOGS_RECIEVED_SUCCESS';
export const LOGS_RECIEVED_ERROR = 'LOGS_RECIEVED_ERROR';


export const COUNT_DOWN_RECIEVED = 'COUNT_DOWN_RECIEVED';
export const COUNT_DOWN_RECIEVED_SUCCESS = 'COUNT_DOWN_RECIEVED_SUCCESS';
export const COUNT_DOWN_RECIEVED_ERROR = 'COUNT_DOWN_RECIEVED_ERROR';


export const SET_PROFILE = 'SET_PROFILE';
export const SET_PROFILE_SUCCESS = 'SET_PROFILE_SUCCESS';
export const SET_PROFILE_ERROR = 'SET_PROFILE_ERROR';

export const SET_PROFILE_STORAGE = 'SET_PROFILE_STORAGE';


export const GET_PROFILE = 'GET_PROFILE';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_ERROR = 'GET_PROFILE_ERROR';


export const GET_NOTIFICATIONS_SOCKET = 'GET_NOTIFICATIONS_SOCKET';

